# Generated by Django 2.0.1 on 2018-01-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0003_auto_20180108_0439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invite',
            options={'get_latest_by': 'created_at'},
        ),
        migrations.AddField(
            model_name='invite',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
