# Generated by Django 2.1.3 on 2018-11-04 22:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0004_auto_20180115_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='tz_count_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
