# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: "website"

# The runtime the application uses.
type: "python:3.8"

# The size of the persistent disk of the application (in MB).
disk: 512  # MB

# The app configuration when it is exposed to the web.
web:
  upstream:
    socket_family: unix
  commands:
    start: "gunicorn --workers 1 --bind unix:$SOCKET --worker-class aiohttp.worker.GunicornUVLoopWebWorker pyslackersweb:app_factory"
  locations:
    "/":
      passthru: true
      allow: false
    "/web/static":
      root: "pyslackersweb/website/static"
      expires: 1h
      allow: true

# The hooks executed at various points in the lifecycle of the application.
hooks:
  build: |
    curl -sS https://platform.sh/cli/installer | php

    pip install -r requirements/production.txt
  deploy: |
    alembic upgrade head

relationships:
  applicationcache: "redisdata:redis"
  database: "database:postgresql"
