[project]
name = "pyslackersweb"
version = "0.0.1"
description = "The website for the pythondev.slack.com community"

[tool.setuptools]
packages = ["pyslackersweb"]

[tool.black]
line-length = 100
target-version = ["py38"]
exclude = """
/(
    \\.git
    | \\.tox
    | \\.venv
    | \\.env
)/
"""
