[tool.black]
line-length = 100
target-version = ["py38", "py312"]
exclude = """
/(
    \\.git
    | \\.tox
    | \\.venv
    | \\.env
)/
"""

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope="function"
