# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 03:27
from __future__ import unicode_literals

from django.db import migrations

from django_celery_beat.models import IntervalSchedule, PeriodicTask


def forward(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    # create the interval for
    Interval: IntervalSchedule = apps.get_model('django_celery_beat',
                                                'IntervalSchedule')
    interval = Interval.objects.using(db_alias).create(every=10,
                                                       period='minutes')

    Task: PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    Task.objects.using(db_alias).create(name='Update Slack Cache',
                                        task='marketing.tasks.update_slack_membership_cache',  # noqa
                                        interval=interval)


def reverse(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Interval: IntervalSchedule = apps.get_model('django_celery_beat',
                                                'IntervalSchedule')
    Interval.objects.using(db_alias).filter(every=10, period='minutes').delete()  # noqa
    Task: PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    Task.objects.using(db_alias).filter(name='Update Slack Cache').delete()


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(forward, reverse),
    ]
