# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 01:18
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Cron = apps.get_model('django_celery_beat', 'CrontabSchedule')
    cron = Cron.objects.using(db_alias).create(minute='0', hour='23',
                                               day_of_week='0')

    Task = apps.get_model('django_celery_beat', 'PeriodicTask')
    Task.objects.using(db_alias) \
        .create(name='Refresh burner email domains',
                task='marketing.tasks.refresh_burner_domain_cache',
                crontab=cron)


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_burnerdomain'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
