"""add SlackChannels & SlackUsers

Revision ID: 2ba5cc3efce8
Revises: 3df042324a1f
Create Date: 2020-07-13 13:12:47.561813+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2ba5cc3efce8"
down_revision = "3df042324a1f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slack_channels",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived", sa.Boolean(), nullable=True),
        sa.Column("members", sa.Integer(), nullable=True),
        sa.Column("topic", sa.Text(), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("ix_slack_channels_id", "slack_channels", ["id"], unique=False)
    op.create_index("ix_slack_channels_name", "slack_channels", ["name"], unique=False)
    op.create_table(
        "slack_users",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("admin", sa.Boolean(), nullable=True),
        sa.Column("bot", sa.Boolean(), nullable=True),
        sa.Column("timezone", sa.Text(), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_slack_users_admin", "slack_users", ["id", "admin"], unique=False)
    op.create_index("ix_slack_users_id", "slack_users", ["id"], unique=False)
    op.create_index("ix_slack_users_timezone", "slack_users", ["id", "timezone"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_slack_users_timezone", table_name="slack_users")
    op.drop_index("ix_slack_users_id", table_name="slack_users")
    op.drop_index("ix_slack_users_admin", table_name="slack_users")
    op.drop_table("slack_users")
    op.drop_index("ix_slack_channels_name", table_name="slack_channels")
    op.drop_index("ix_slack_channels_id", table_name="slack_channels")
    op.drop_table("slack_channels")
    # ### end Alembic commands ###
