"""create email domains

Revision ID: b1362f9fad30
Revises: 
Create Date: 2020-01-24 02:59:46.288204+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1362f9fad30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('WESBOS', 'INVITE', 'MANUAL', name='source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_index('ix_domain_blocked', 'domains', ['domain', 'blocked'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_domain_blocked', table_name='domains')
    op.drop_table('domains')
    # ### end Alembic commands ###
