"""add sirbot tables

Revision ID: f7f15f30aeee
Revises: dece77ed5036
Create Date: 2021-01-12 20:42:45.644752+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f7f15f30aeee"
down_revision = "dece77ed5036"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "slack_messages",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("send_at", sa.DateTime(), nullable=True),
        sa.Column("user", sa.Text(), nullable=True),
        sa.Column("channel", sa.Text(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_slack_messages_channel", "slack_messages", ["channel", "send_at"], unique=False
    )
    op.create_index("ix_slack_messages_user", "slack_messages", ["user", "send_at"], unique=False)
    op.create_index(
        "ix_slack_messages_user_channel",
        "slack_messages",
        ["user", "channel", "send_at"],
        unique=False,
    )
    op.add_column("slack_users", sa.Column("name", sa.Text(), nullable=True))
    op.create_index("ix_slack_users_name", "slack_users", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_slack_users_name", table_name="slack_users")
    op.drop_column("slack_users", "name")
    op.drop_index("ix_slack_messages_user_channel", table_name="slack_messages")
    op.drop_index("ix_slack_messages_user", table_name="slack_messages")
    op.drop_index("ix_slack_messages_channel", table_name="slack_messages")
    op.drop_table("slack_messages")
    # ### end Alembic commands ###
