"""init codewars challenge

Revision ID: dece77ed5036
Revises: 2ba5cc3efce8
Create Date: 2021-01-04 20:23:50.479134+00:00

"""

from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dece77ed5036"
down_revision = "2ba5cc3efce8"
branch_labels = None
depends_on = None

QUESTIONS = [
    "550f22f4d758534c1100025a",
    "525f3eda17c7cd9f9e000b39",
    "54521e9ec8e60bc4de000d6c",
    "52bb6539a4cf1b12d90005b7",
    "5296bc77afba8baa690002d7",
    "5235c913397cbf2508000048",
    "521c2db8ddc89b9b7a0000c1",
    "55983863da40caa2c900004e",
    "52742f58faf5485cae000b9a",
    "52a78825cdfc2cfc87000005",
    "54acd76f7207c6a2880012bb",
    "5679d5a3f2272011d700000d",
]

codewars = sa.sql.table(
    "codewars_challenge",
    sa.Column("id", sa.Text, primary_key=True),
    sa.Column("added_at", sa.DateTime(timezone=True), default=datetime.now, nullable=False),
    sa.Column(
        "posted_at",
        sa.DateTime(timezone=True),
        default=None,
        onupdate=datetime.now,
        nullable=True,
    ),
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "codewars_challenge",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False, default=datetime.utcnow),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    op.bulk_insert(codewars, [{"id": q} for q in QUESTIONS])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("codewars_challenge")
    # ### end Alembic commands ###
