# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 04:25
from __future__ import unicode_literals

from django.db import migrations, models


def forward(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Cron = apps.get_model('django_celery_beat', 'CrontabSchedule')
    cron = Cron.objects.using(db_alias).create(minute='0', hour='0')

    Task = apps.get_model('django_celery_beat', 'PeriodicTask')
    Task.objects.using(db_alias).create(name='Capture slack membership counts',
                                        task='marketing.tasks.capture_snapshot_of_user_count',  # noqa
                                        crontab=cron)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_count', models.IntegerField()),
                ('deleted_count', models.IntegerField()),
                ('bot_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(forward),
    ]
