# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 03:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_auto_20170729_2047'),
        ('marketing', '0005_remove-celerybeat-tasks-from-database-directly'),
    ]

    operations = [
    ]
