"https://{default}/":
  type: upstream
  upstream: "website:http"
  redirects:
    expires: 1d
    paths:
      '/':
        to: "/web"
        prefix: false

"https://www.{default}/":
  type: redirect
  to: "https://{default}"
