"https://{default}/":
  type: upstream
  upstream: "website:http"
  cache:
    enabled: true
    default_ttl: 3600
  redirects:
    paths:
      '/':
        to: "/web"
        prefix: false

"https://www.{default}/":
  type: redirect
  to: "https://{default}"
