# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnerDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.TextField(unique=True)),
            ],
        ),
    ]
