# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_add_scheduled_task_for_burner_domain_refreshes'),
    ]

    state_operations = [
        migrations.DeleteModel('Membership'),
    ]

    database_operations = [
        migrations.AlterModelTable('Membership', 'slack_membership')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
        )
    ]
