# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 01:26
from __future__ import unicode_literals

from django.db import migrations


def delete_migrated_tasks(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')

    PeriodicTask.objects.filter(task__startswith="marketing.tasks.").delete()
    PeriodicTask.objects.filter(task__startswith="slack.tasks.").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_add_scheduled_task_for_burner_domain_refreshes'),
    ]

    operations = [
        migrations.RunPython(delete_migrated_tasks),
    ]
